spring:
  application:
    name: Expense Tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: vinish
    password: test123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
